### ISSUE TITLE
Initial view

### ISSUE THREAD

**Issue by Peter9192** [classmodel/class-web#63]
I was thinking about the ux, and that perhaps it would be nice, if a user first lands on the page, to have a dialog like so:

![image](https://github.com/user-attachments/assets/31e94025-23d3-46be-a19f-690bdb3b7340)

(excuse the ppt mockup...)

Preset could be a dropdown?

**Comment by sverhoeven** [comment]
That could work.
1. `Resume form previous session`, should only be shown if there is a previous session. We could use [onCleanup()](https://docs.solidjs.com/reference/lifecycle/on-cleanup) to store the app state as JSON string in [localstorage](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage#storing_simple_data_%E2%80%94_web_storage).
2. The `link` button is not useful, a person with a shared link will directly load the experiment and not see this screen.
3. `From preset`could instead of a dropdown, could be a a expanding window which give more room to explain each preset.

**Comment by sverhoeven** [comment]
Link could also link to another application that can link to the class webapp with a state in the url
